// Dashboard
export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_RECEIVE = 'DASHBOARD_RECEIVE';
export const DASHBOARD_RECEIVE_FAILED = 'DASHBOARD_RECEIVE_FAILED';

// Mailing
export const MAILING_REQUEST = 'MAILING_REQUEST';
export const MAILING_RECEIVE = 'MAILING_RECEIVE';
export const MAILING_RECEIVE_FAILED = 'MAILING_RECEIVE_FAILED';